export const ROUTES = {
  home: '/',
  videos: '/videos',
  login: '/login',
  register: '/register',
  studio: '/studio',
  dashboard: {
    root: '/dashboard',
    videos: '/dashboard/videos',
    services: '/dashboard/services',
    tariffs: '/dashboard/tariffs',
    advantages: '/dashboard/advantages',
    banner: '/dashboard/banner',
    products: '/dashboard/products',
    chatDemo: '/dashboard/chat-demo',
    leads: '/dashboard/leads',
    users: '/dashboard/users',
    settings: '/dashboard/settings',
  },
} as const
